server:
  port: 7777

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useSSL=false
    username: bitai
    password: 456123
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    mode: HTML
    cache: false
    order: 0
  jpa:
    open-in-view: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      fail-on-empty-beans: false

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
    app:
      sample:
        messages:
          AuditingFilter: DEBUG
          SecurityChecker: DEBUG
          MessageService: DEBUG